import { Platform, StyleSheet, useColorScheme, Dimensions } from "react-native";

// --- Palettes ---
export const LightPalette = {
    primary: '#6F4E37',
    background: '#e1d7c9ff',
    card: '#FFFFFF',
    textMain: '#2D2D2D',
    textMuted: '#666',
    inputBg: '#FFFFFF',
    inputBorder: '#E2E8F0',
    headerText: '#FFFFFF',
    badge: '#6F4E37',
    badgeText: '#FFFFFF',
    claimBtn: '#FFFFFF',
    recentCard: '#FFFFFF',
    recentBorder: '#F1F5F9',
    reorderBtn: '#F3F0EE',
    shadow: '#000',
    terracotta: '#D17842',
};

export const DarkPalette = {
    primary: '#6F4E37',
    background: '#121212',
    card: '#1E1E1E',
    textMain: '#F1F5F9',
    textMuted: '#94A3B8',
    inputBg: '#2D2D2D',
    inputBorder: '#404040',
    headerText: '#F1F5F9',
    badge: '#6F4E37',
    badgeText: '#FFFFFF',
    claimBtn: '#2D2D2D',
    recentCard: '#1E1E1E',
    recentBorder: '#2D2D2D',
    reorderBtn: '#2D2D2D',
    shadow: '#000',
    terracotta: '#D17842',
};

// --- Style Factory ---
const createStyles = (theme) => StyleSheet.create({
    homepageContainer: {
        flex: 1,
        backgroundColor: theme.background,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
    },
    container: {
        flex: 1,
        backgroundColor: theme.background,
        marginTop: Platform.OS === 'ios' ? 40 : 30,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 20,
        marginTop: Platform.OS === 'ios' ? 40 : 30,
    },
    greetingText: {
        fontSize: 16,
        color: theme.textMuted,
    },
    userName: {
        fontSize: 22,
        fontWeight: 'bold',
        color: theme.textMain,
    },
    profileAvatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
    },
    searchContainer: {
        paddingHorizontal: 20,
        marginTop: 20,
    },
    searchInput: {
        backgroundColor: theme.inputBg,
        height: 50,
        borderRadius: 15,
        paddingHorizontal: 20,
        fontSize: 16,
        color: theme.textMain,
        borderWidth: theme.background === '#121212' ? 1 : 0,
        borderColor: theme.inputBorder,
    },
    promoCard: { width: '100%', height: '100%' },
    promoOverlay: {
        flex: 1,
        padding: 15,
        backgroundColor: 'rgba(0,0,0,0.3)',
        borderRadius: 20,
    },
    dealBadge: {
        backgroundColor: theme.primary,
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 5,
        marginBottom: 10,
    },
    dealBadgeText: { color: '#FFF', fontSize: 12, fontWeight: 'bold' },
    promoTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold' },
    promoValidity: { color: '#EEE', fontSize: 12, marginTop: 5 },
    claimButton: {
        backgroundColor: theme.claimBtn,
        paddingHorizontal: 20,
        paddingVertical: 8,
        borderRadius: 20,
        alignSelf: 'flex-start',
        marginTop: 15,
    },
    claimButtonText: { color: theme.primary, fontWeight: 'bold', fontSize: 14 },
    sectionTitle: { fontSize: 18, fontWeight: 'bold', color: theme.textMain },
    recommendedContainer: { display: 'flex', paddingLeft: 20, gap: 10, marginBottom: 15 },
    recommendedCard: { width: 150, marginRight: 15 },
    recommendedTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 2, color: theme.textMain },
    recommendedDescription: { fontSize: 12, color: theme.textMuted, marginBottom: 5 },
    recommendedPrice: { fontSize: 14, fontWeight: 'bold', color: theme.primary },
    recommendedImage: { width: '100%', height: 135, borderRadius: 15, marginBottom: 10, marginTop: 20 },
    recentOrdersContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20 },
    recentOrdersTitle: { fontSize: 18, fontWeight: 'bold', color: theme.textMain },
    recentOrdersCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.recentCard,
        marginHorizontal: 20,
        marginBottom: 12,
        padding: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: theme.recentBorder,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    recentOrdersImage: { width: 65, height: 65, borderRadius: 15 },
    recentOrdersName: { fontSize: 16, fontWeight: 'bold', marginBottom: 2, color: theme.textMain },
    recentOrdersDescription: { fontSize: 13, color: theme.textMuted },
    recentOrdersReorderBtn: { backgroundColor: theme.reorderBtn, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 15 },
    recentOrdersReorderText: { color: theme.primary, fontWeight: '700', fontSize: 14 },

    // --- High-Fidelity Visual Restorations ---
    authVisualHeader: {
        height: Dimensions.get('window').height * 0.38, // Reduced height for better proportions
        // height: '35%',
        backgroundColor: theme.primary,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        overflow: 'hidden',
        position: 'relative',
    },
    authVisualHeadersignup: {
        // height: Dimensions.get('window').height * 0.38, // Reduced height for better proportions
        height: '34%',
        backgroundColor: theme.primary,
        overflow: 'hidden',
        position: 'relative',
    },
    authVisualHeaderlogin: {
        // height: Dimensions.get('window').height * 0.38, // Reduced height for better proportions
        height: '38%',
        backgroundColor: theme.primary,
        // borderBottomLeftRadius: 40,
        // borderBottomRightRadius: 40,
        overflow: 'hidden',
        position: 'relative',
    },
    menuheader: {
        paddingTop: Platform.OS === 'ios' ? 50 : 20,
        paddingHorizontal: 20,
        backgroundColor: theme.background,
    },
    menuHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    menuTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.textMain,
    },
    menuSearchContainer: {
        backgroundColor: theme.card,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 15,
        height: 50,
        borderRadius: 15,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
        marginBottom: 20,
    },
    menuSearchInput: {
        flex: 1,
        marginLeft: 10,
        fontSize: 16,
        color: theme.textMain,
    },
    categoryContainer: {
        flexDirection: 'row',
        marginBottom: 25,
    },
    categoryChip: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: theme.card,
        marginRight: 10,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    categoryChipActive: {
        backgroundColor: theme.primary,
    },
    categoryText: {
        color: theme.textMuted,
        fontWeight: '600',
    },
    categoryTextActive: {
        color: '#FFFFFF',
    },
    menuItemCard: {
        backgroundColor: theme.card,
        borderRadius: 25,
        padding: 15,
        flexDirection: 'row',
        marginBottom: 15,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 15,
        elevation: 2,
    },
    menuItemImage: {
        width: 100,
        height: 100,
        borderRadius: 20,
    },
    menuItemInfo: {
        flex: 1,
        marginLeft: 15,
        justifyContent: 'space-between',
    },
    menuItemName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.textMain,
    },
    menuItemDescription: {
        fontSize: 12,
        color: theme.textMuted,
        marginTop: 4,
    },
    menuItemFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 10,
    },
    menuItemPrice: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.terracotta,
    },
    menuItemAddBtn: {
        backgroundColor: theme.terracotta,
        width: 35,
        height: 35,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    authVisualHeaderImage: {
        width: '100%',
        height: '100%',
        position: 'absolute',
    },
    headerGradient: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '60%', // Cover bottom half of header for smooth fade
    },
    morningRitualsTitle: {
        fontSize: 28, // Slighly smaller font
        fontWeight: 'bold',
        color: theme.textMain,
        marginTop: 25,
        paddingHorizontal: 30,
    },
    morningRitualsSubtitle: {
        fontSize: 16,
        color: theme.textMuted,
        paddingHorizontal: 30,
        marginBottom: 30,
    },
    terracottaBtn: {
        backgroundColor: '#6F4E37',
        marginHorizontal: 30,
        paddingVertical: 16, // Slighly reduced padding
        borderRadius: 18,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
        shadowColor: "#6F4E37",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
    },
    terracottaBtnText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '700',
        marginRight: 10,
    },
    logincontainer: {
        flex: 1,
        backgroundColor: theme.background,
    },
    inputContainer: {
        marginBottom: 20,
        paddingHorizontal: 30,
    },
    inputLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.textMuted,
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.background === '#121212' ? '#1E1E1E' : '#FFFFFF',
        borderRadius: 15,
        paddingHorizontal: 15,
        height: 55, // Reduced height
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    textInput: {
        flex: 1,
        fontSize: 16,
        color: theme.textMain,
        marginLeft: 10,
        height: '100%',
    },
    forgotPasswordText: {
        color: '#6F4E37',
        fontSize: 14,
        fontWeight: 'bold',
        alignSelf: 'flex-end',
        marginRight: 30,
        marginBottom: 20,
    },
    signupFooter: {
        marginTop: 20,
        marginBottom: 30,
        flexDirection: 'row',
        justifyContent: 'center',
    },
    welcomeWrapper: {
        flex: 1,
        backgroundColor: theme.background,
    },
    header: {
        paddingTop: 30,
        paddingHorizontal: 30,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: theme.headerText,
        letterSpacing: -0.5,
        marginTop: 20,
    },
    card: {
        backgroundColor: theme.card,
        marginHorizontal: 25,
        marginTop: -60, // Overlay effect
        padding: 30,
        borderRadius: 35,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 8,
    },
    cardTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.textMain,
        marginBottom: 12,
    },
    bodyText: {
        fontSize: 16,
        color: theme.textMuted,
        lineHeight: 24,
        marginBottom: 30,
    },
    buttonMain: {
        backgroundColor: '#6F4E37',
        paddingVertical: 16,
        borderRadius: 20,
        alignItems: 'center',
        marginBottom: 15,
    },
    buttonTextMain: {
        color: '#FFFFFF',
        fontSize: 17,
        fontWeight: 'bold',
    },
    buttonSecondary: {
        backgroundColor: 'transparent',
        paddingVertical: 16,
        borderRadius: 20,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#6F4E37',
    },
    buttonTextSecondary: {
        color: '#6F4E37',
        fontSize: 17,
        fontWeight: 'bold',
    },
    // --- Detail Page Styles ---
    detailHeroContainer: {
        width: '100%',
        height: 350,
        position: 'relative',
    },
    detailHeroImage: {
        width: '100%',
        height: '100%',
        backgroundColor: '#000000',
        opacity: 0.8,
    },
    detailHeaderButtons: {
        position: 'absolute',
        top: 50,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
    },
    iconCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailContent: {
        padding: 25,
        backgroundColor: theme.background,
        borderTopLeftRadius: 35,
        borderTopRightRadius: 35,
        marginTop: -30,
    },
    detailTitlePriceRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    detailTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: theme.textMain,
        flex: 1,
    },
    detailPrice: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.primary,
    },
    detailRatingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
    },
    detailRatingText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.textMain,
        marginLeft: 5,
    },
    detailReviewsText: {
        fontSize: 14,
        color: theme.textMuted,
        marginLeft: 5,
    },
    detailDescription: {
        fontSize: 15,
        color: theme.textMuted,
        lineHeight: 22,
        marginTop: 15,
    },
    detailSectionHeader: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.textMuted,
        marginTop: 25,
        marginBottom: 15,
        textTransform: 'uppercase',
    },
    sizeSelectionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    sizeOption: {
        width: '30%',
        paddingVertical: 15,
        borderRadius: 15,
        borderWidth: 1.5,
        borderColor: theme.card,
        alignItems: 'center',
        backgroundColor: theme.card,
    },
    sizeOptionActive: {
        borderColor: theme.terracotta,
        backgroundColor: theme.background,
    },
    sizeLabel: {
        marginTop: 8,
        fontSize: 14,
        fontWeight: '600',
        color: theme.textMuted,
    },
    sizeLabelActive: {
        color: theme.terracotta,
    },
    choiceChipsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    choiceChip: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 25,
        backgroundColor: theme.card,
        marginRight: 10,
        marginBottom: 10,
    },
    choiceChipActive: {
        backgroundColor: theme.terracotta,
    },
    choiceChipText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.textMuted,
    },
    choiceChipTextActive: {
        color: '#FFFFFF',
    },
    bottomBasketBar: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
        paddingBottom: 35,
        backgroundColor: theme.background,
        borderTopWidth: 1,
        borderTopColor: theme.card,
    },
    detailQuantitySelector: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.card,
        borderRadius: 15,
        paddingHorizontal: 15,
        height: 55,
        marginRight: 15,
    },
    quantityBtn: {
        padding: 5,
    },
    quantityText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.textMain,
        marginHorizontal: 15,
    },
    detailAddToCartBtn: {
        flex: 1,
        backgroundColor: theme.primary,
        height: 55,
        borderRadius: 15,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailAddToCartText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 10,
    },
});

// --- Hook ---
export const useAppStyles = () => {
    const colorScheme = useColorScheme();
    const isDark = colorScheme === 'dark';
    const theme = isDark ? DarkPalette : LightPalette;
    const styles = createStyles(theme);

    return { styles, theme, isDark };
};